"""Tests for Antigravity graceful shutdown mechanism.

Static tests verify configuration correctness (no Docker required).
Integration tests spin up a kasm container and verify actual docker stop/restart
triggers the SIGTERM trap and graceful shutdown handler in entrypoint.sh.
"""
import pytest
import subprocess
import os
import shlex
import time

import yaml

from tests.utils import wait_for_log
from tests.conftest import DEFAULT_KASM_IMAGE


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

# Dynamic compose is now generated by the sanity_gravity package; import the
# helper from the new location.
import sys
sys.path.insert(0, os.path.abspath(
    os.path.join(os.path.dirname(__file__), "..", "..")
))


def _load_sanity_cli():
    """Return the compose-generator module so callers can keep reading
    ``cli.generate_compose_for_tag(...)``."""
    from sanity_gravity.compose import generators as cg
    return cg


ENTRYPOINT_FILE = os.path.join(
    os.path.dirname(__file__),
    "..", "..", "sandbox", "rootfs", "usr", "local", "bin", "entrypoint.sh",
)
AG_SHUTDOWN_FILE = os.path.join(
    os.path.dirname(__file__),
    "..", "..", "plugins", "agents", "ag", "rootfs", "etc", "shutdown.d", "10-ag-shutdown.sh",
)
DOCKERFILE_BASE = os.path.join(
    os.path.dirname(__file__),
    "..", "..", "plugins", "base-images", "ubuntu", "Dockerfile",
)

CONTAINER_STARTUP_TIMEOUT = 30  # seconds to wait for kasm + X session


def _load_compose_for_tag(tag):
    cli = _load_sanity_cli()
    compose_path, _ = cli.generate_compose_for_tag(tag)
    with open(compose_path) as f:
        return yaml.safe_load(f)


def _read_file(path):
    with open(path) as f:
        return f.read()


def _run(cmd, check=False):
    return subprocess.run(cmd, shell=True, capture_output=True, text=True, check=check)


def _docker_exec(container, cmd, user=None):
    if user:
        full = f"docker exec {container} su - {user} -c {shlex.quote(cmd)}"
    else:
        full = f"docker exec {container} bash -c {shlex.quote(cmd)}"
    return _run(full)


# ---------------------------------------------------------------------------
# Static tests (no Docker needed)
# ---------------------------------------------------------------------------

class TestGracefulShutdownConfig:
    """Verify static configuration for graceful shutdown."""

    def test_stop_grace_period_kasm(self):
        """Dynamic compose for kasm connector includes stop_grace_period."""
        compose = _load_compose_for_tag("ag-xfce-kasm")
        assert compose["services"]["ag-xfce-kasm"]["stop_grace_period"] == "30s"

    def test_stop_grace_period_vnc(self):
        """Dynamic compose for vnc connector includes stop_grace_period."""
        compose = _load_compose_for_tag("ag-xfce-vnc")
        assert compose["services"]["ag-xfce-vnc"]["stop_grace_period"] == "30s"

    def test_entrypoint_has_sigterm_trap(self):
        content = _read_file(ENTRYPOINT_FILE)
        assert "trap graceful_shutdown SIGTERM" in content

    def test_ag_shutdown_hook_has_xdotool_ctrl_q(self):
        content = _read_file(AG_SHUTDOWN_FILE)
        assert "xdotool key --window" in content
        assert "ctrl+q" in content

    def test_entrypoint_does_not_exec_supervisord(self):
        """PID 1 must be bash (not supervisord) so trap works."""
        content = _read_file(ENTRYPOINT_FILE)
        lines = content.strip().splitlines()
        tail = "\n".join(lines[-5:])
        assert 'exec "$@"' not in tail

    def test_entrypoint_runs_supervisord_in_background(self):
        content = _read_file(ENTRYPOINT_FILE)
        assert '"$@" &' in content
        assert "SUPERVISOR_PID=$!" in content

    def test_entrypoint_waits_for_supervisor(self):
        content = _read_file(ENTRYPOINT_FILE)
        assert 'wait "$SUPERVISOR_PID"' in content

    def test_entrypoint_forwards_sigterm_to_supervisor(self):
        content = _read_file(ENTRYPOINT_FILE)
        assert 'kill -TERM "$SUPERVISOR_PID"' in content

    def test_dockerfile_installs_xdotool(self):
        content = _read_file(DOCKERFILE_BASE)
        # xdotool is in the desktop layer, check base has core deps
        # or check the xfce desktop layer
        xfce_layer = os.path.join(
            os.path.dirname(__file__),
            "..", "..", "plugins", "desktops", "xfce", "Dockerfile",
        )
        layer_content = _read_file(xfce_layer)
        assert "xdotool" in layer_content

    def test_ag_shutdown_hook_filters_helper_windows(self):
        """Must filter by window name to skip antigravity-bin helper windows."""
        content = _read_file(AG_SHUTDOWN_FILE)
        assert '" - Antigravity"' in content

# ---------------------------------------------------------------------------
# Integration tests (self-contained: spin up own container)
# ---------------------------------------------------------------------------

@pytest.fixture(scope="class")
def graceful_container(request):
    """Spin up a kasm container for graceful shutdown testing.

    Uses scope="class" so the container is shared across tests in a class
    and rebuilt (via docker start) when a test stops it.
    """
    name = "sanity-test-graceful-shutdown"
    uid = str(os.getuid())
    gid = str(os.getgid())
    user = os.getenv("USER", "testuser")

    # Clean up any leftover from previous runs
    _run(f"docker rm -f {name}")

    # Start container (--rm=False so we can restart it)
    env_flags = (
        f"-e HOST_UID={uid} -e HOST_GID={gid} "
        f"-e HOST_USER={user} -e HOST_PASSWORD=testpassword"
    )
    _run(
        f"docker run -d --name {name} --shm-size=512m "
        f"{env_flags} {DEFAULT_KASM_IMAGE}",
        check=True,
    )

    # Wait for kasm + X session to be ready
    assert wait_for_log(name, "success: kasmvnc", timeout=CONTAINER_STARTUP_TIMEOUT), \
        "Container did not start kasmvnc in time"

    yield name, user

    # Cleanup
    _run(f"docker rm -f {name}")


class TestGracefulShutdownIntegration:
    """Integration tests that spin up their own kasm container."""

    def test_xdotool_available(self, graceful_container):
        name, user = graceful_container
        r = _docker_exec(name, "which xdotool", user=user)
        assert r.returncode == 0, "xdotool not found in container"

    def test_pid1_is_entrypoint_not_supervisord(self, graceful_container):
        """PID 1 must be the entrypoint shell (not supervisord) for trap to work."""
        name, _ = graceful_container
        r = _docker_exec(name, "cat /proc/1/comm")
        comm = r.stdout.strip()
        assert comm not in ("supervisord", "python3"), \
            f"PID 1 is {comm}, expected entrypoint shell"

    def test_supervisor_running(self, graceful_container):
        name, _ = graceful_container
        r = _docker_exec(name, "pgrep -c supervisord")
        assert int(r.stdout.strip()) >= 1

    def test_docker_stop_triggers_graceful_handler(self, graceful_container):
        """docker stop should trigger the SIGTERM trap and log the shutdown message."""
        name, _ = graceful_container

        # Stop the container (SIGTERM → trap → graceful_shutdown())
        r = _run(f"docker stop -t 30 {name}")
        assert r.returncode == 0, f"docker stop failed: {r.stderr}"

        # Check container logs for the graceful shutdown message
        logs = _run(f"docker logs {name}").stdout + _run(f"docker logs {name}").stderr
        assert "[shutdown] Graceful shutdown initiated" in logs, \
            f"Graceful shutdown handler was not triggered. Logs:\n{logs[-500:]}"

        # Restart for subsequent tests
        _run(f"docker start {name}", check=True)
        assert wait_for_log(name, "Starting Antigravity Sandbox", timeout=CONTAINER_STARTUP_TIMEOUT)
        # Wait for supervisord to be fully ready
        time.sleep(3)

    def test_docker_restart_triggers_graceful_handler(self, graceful_container):
        """docker restart should also trigger the SIGTERM trap."""
        name, _ = graceful_container

        # Clear previous logs by noting current log length
        logs_before = _run(f"docker logs {name}").stdout
        marker_count_before = logs_before.count("[shutdown] Graceful shutdown initiated")

        # Restart the container
        r = _run(f"docker restart -t 30 {name}")
        assert r.returncode == 0, f"docker restart failed: {r.stderr}"

        # Wait for container to be back up
        assert wait_for_log(name, "Starting Antigravity Sandbox", timeout=CONTAINER_STARTUP_TIMEOUT)
        time.sleep(3)

        # Check that a NEW graceful shutdown message appeared
        logs_after = _run(f"docker logs {name}").stdout
        marker_count_after = logs_after.count("[shutdown] Graceful shutdown initiated")
        assert marker_count_after > marker_count_before, \
            "docker restart did not trigger a new graceful shutdown"

    def test_supervisor_recovers_after_restart(self, graceful_container):
        """After docker restart, supervisord should be running again."""
        name, _ = graceful_container
        r = _docker_exec(name, "pgrep -c supervisord")
        assert int(r.stdout.strip()) >= 1
